// One-time script: pull exercises from WorkoutX API and bundle locally.
// Run: node scripts/fetchExercises.mjs
// Outputs: src/data/exerciseLibrary.js + downloads GIFs to public/gifs/

import { writeFileSync, existsSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dir = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dir, '..')
const GIF_DIR = join(ROOT, 'public', 'gifs')

const BASE = 'https://api.workoutxapp.com/v1'
const KEY = 'wx_419d7e78264b999296d35cf96668bd7494ddf9f97b2998c295e17771'
const HEADERS = { 'X-WorkoutX-Key': KEY }

// Equipment relevant to the user's home gym
const EQUIPMENT = ['dumbbell', 'resistance band', 'body weight']

// Body parts to include (skip machine-only body parts)
const BODY_PARTS_KEEP = [
  'chest', 'back', 'shoulders', 'upper arms', 'lower arms',
  'upper legs', 'lower legs', 'waist', 'glutes', 'neck'
]

const sleep = ms => new Promise(r => setTimeout(r, ms))

async function fetchAll(path) {
  const res = await fetch(`${BASE}${path}`, { headers: HEADERS })
  if (!res.ok) throw new Error(`${res.status} ${path}`)
  const json = await res.json()
  return json.data || []
}

async function downloadGif(id) {
  const dest = join(GIF_DIR, `${id}.gif`)
  if (existsSync(dest)) {
    console.log(`  skip ${id}.gif (already exists)`)
    return true
  }
  const url = `${BASE}/gifs/${id}.gif?api-key=${KEY}`
  try {
    const res = await fetch(url)
    if (!res.ok) { console.log(`  ✗ ${id}.gif (${res.status})`); return false }
    const buf = await res.arrayBuffer()
    writeFileSync(dest, Buffer.from(buf))
    console.log(`  ✓ ${id}.gif (${Math.round(buf.byteLength / 1024)}KB)`)
    return true
  } catch (e) {
    console.log(`  ✗ ${id}.gif (${e.message})`)
    return false
  }
}

async function main() {
  mkdirSync(GIF_DIR, { recursive: true })

  // --- 1. Fetch exercises by equipment ---
  const seen = new Map() // id → exercise

  for (const eq of EQUIPMENT) {
    console.log(`\nFetching equipment: ${eq}`)
    const encoded = encodeURIComponent(eq)
    // Try limits of 50 and offset 0, then 50 (to get up to 100)
    for (const offset of [0, 50]) {
      await sleep(300)
      const items = await fetchAll(`/exercises/equipment/${encoded}?limit=50&offset=${offset}`)
      if (!items.length) break
      for (const ex of items) {
        const bp = (ex.bodyPart || '').toLowerCase()
        if (!BODY_PARTS_KEEP.includes(bp)) continue
        if (!seen.has(ex.id)) seen.set(ex.id, ex)
      }
      console.log(`  offset ${offset}: ${items.length} items, total unique: ${seen.size}`)
      if (items.length < 50) break
    }
  }

  console.log(`\nTotal unique exercises: ${seen.size}`)

  // --- 2. Download GIFs ---
  console.log('\nDownloading GIFs...')
  const exercises = [...seen.values()]
  let downloaded = 0
  for (const ex of exercises) {
    const ok = await downloadGif(ex.id)
    if (ok) downloaded++
    await sleep(150) // gentle rate limit
  }
  console.log(`\nGIFs: ${downloaded}/${exercises.length} downloaded`)

  // --- 3. Save exercise library JSON ---
  // Strip fields we don't need to keep the file small
  const library = exercises.map(ex => ({
    id: ex.id,
    name: ex.name,
    bodyPart: (ex.bodyPart || '').toLowerCase(),
    equipment: (ex.equipment || '').toLowerCase(),
    target: (ex.target || '').toLowerCase(),
    secondaryMuscles: (ex.secondaryMuscles || []).map(m => m.toLowerCase()),
    instructions: ex.instructions || [],
  }))

  // Sort by body part then name for readability
  library.sort((a, b) => a.bodyPart.localeCompare(b.bodyPart) || a.name.localeCompare(b.name))

  const js = `// Auto-generated by scripts/fetchExercises.mjs — do not edit manually.
// ${library.length} exercises from WorkoutX API, bundled locally (zero API calls at runtime).
const EXERCISE_LIBRARY = ${JSON.stringify(library, null, 2)}

export default EXERCISE_LIBRARY
`

  const outPath = join(ROOT, 'src', 'data', 'exerciseLibrary.js')
  writeFileSync(outPath, js)
  console.log(`\nSaved ${library.length} exercises to src/data/exerciseLibrary.js`)
  console.log('Done! You can now delete scripts/fetchExercises.mjs if you wish.')
}

main().catch(e => { console.error(e); process.exit(1) })
